#!/bin/bash
     
## Script iptables by Dlugosz Tristan.
    
## Règles iptables.
     
## On flush iptables.

IPTABLEPATH="/usr/sbin"


	## filter : C'est la table par défaut (si l'option -t est omise). Elle contient les chaînes prédéfinies INPUT (pour les paquets
	## entrants dans la machine), FORWARD (pour les paquets routés à travers la machine) et OUTPUT (pour les paquets générés localement). 


# Flush des chaines (efface les règles prédéfinies)
$IPTABLEPATH/iptables -F
# Delete des chaines (efface les règle non-prédéfinies)
$IPTABLEPATH/iptables -X

	## nat: Cette table est consultée lorsqu'on rencontre un paquet qui crée une nouvelle connexion.


# Flush des chaines (efface les règles prédéfinies)
$IPTABLEPATH/iptables -t nat -F
# Delete des chaines (efface les règle non-prédéfinies)
$IPTABLEPATH/iptables -t nat -X

	## mangle : Cette table est employée pour effectuer une modification spéciale des paquets.


# Flush des chaines (efface les règles prédéfinies)
$IPTABLEPATH/iptables -t mangle -F
# Delete des chaines (efface les règle non-prédéfinies)
$IPTABLEPATH/iptables -t mangle -X
     
## On drop les requêtes ICMP (votre machine ne répondra plus aux requêtes ping sur votre réseau local).
     
$IPTABLEPATH/iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
$IPTABLEPATH/iptables -A OUTPUT -p icmp --icmp-type echo-reply -j DROP
     
    ## On accepte le Multicast.
     
# $IPTABLEPATH/iptables -A INPUT -m pkttype --pkt-type multicast -j ACCEPT
     
## On drop tout le trafic entrant.
     
$IPTABLEPATH/iptables -P INPUT DROP
     
    ## On drop tout le trafic sortant.
     
$IPTABLEPATH/iptables -P OUTPUT DROP
     
    ## On drop le forward.
     
$IPTABLEPATH/iptables -P FORWARD DROP
     
    ## On drop les scans XMAS et NULL.
     
$IPTABLEPATH/iptables -A INPUT -m conntrack --ctstate INVALID -p tcp --tcp-flags FIN,URG,PSH FIN,URG,PSH -j DROP
     
$IPTABLEPATH/iptables -A INPUT -m conntrack --ctstate INVALID -p tcp --tcp-flags ALL ALL -j DROP
     
$IPTABLEPATH/iptables -A INPUT -m conntrack --ctstate INVALID -p tcp --tcp-flags ALL NONE -j DROP
     
$IPTABLEPATH/iptables -A INPUT -m conntrack --ctstate INVALID -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
     
## Dropper silencieusement tous les paquets broadcastés.
     
$IPTABLEPATH/iptables -A INPUT -m pkttype --pkt-type broadcast -j DROP


	## INTERNAL NETWORK
	
#Allow trafic on internal network
$IPTABLEPATH/iptables -t filter -A INPUT -i lo -j ACCEPT
$IPTABLEPATH/iptables -t filter -A OUTPUT -o lo -j ACCEPT

#Allow ping to internal network
# $IPTABLEPATH/iptables -A OUTPUT -o eth0 -p icmp -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT
# $IPTABLEPATH/iptables -A INPUT -i eth0 -p icmp -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT
     
	## WEB

# Rules for web	
# $IPTABLEPATH/iptables -t filter -A OUTPUT -p tcp -m multiport --dports 80,443,8000 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
# $IPTABLEPATH/iptables -t filter -A INPUT -p tcp -m multiport --sports 80,443,8000 -m conntrack --ctstate ESTABLISHED -j ACCEPT

## Permettre à une connexion ouverte de recevoir du trafic en entrée.
 
$IPTABLEPATH/iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
 
## Permettre à une connexion ouverte de recevoir du trafic en sortie.
 
$IPTABLEPATH/iptables -A OUTPUT -m conntrack ! --ctstate INVALID -j ACCEPT
     

     


exit 0

